/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LeafComponent {
    }
    interface ParentComponent {
    }
}
declare global {
    interface HTMLLeafComponentElement extends Components.LeafComponent, HTMLStencilElement {
    }
    var HTMLLeafComponentElement: {
        prototype: HTMLLeafComponentElement;
        new (): HTMLLeafComponentElement;
    };
    interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {
    }
    var HTMLParentComponentElement: {
        prototype: HTMLParentComponentElement;
        new (): HTMLParentComponentElement;
    };
    interface HTMLElementTagNameMap {
        "leaf-component": HTMLLeafComponentElement;
        "parent-component": HTMLParentComponentElement;
    }
}
declare namespace LocalJSX {
    interface LeafComponent {
    }
    interface ParentComponent {
    }
    interface IntrinsicElements {
        "leaf-component": LeafComponent;
        "parent-component": ParentComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "leaf-component": LocalJSX.LeafComponent & JSXBase.HTMLAttributes<HTMLLeafComponentElement>;
            "parent-component": LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
        }
    }
}
