/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlantCard {
        "hostRole"?: 'button' | 'link';
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "role"?: 'button' | 'link';
    }
    interface PlantList {
    }
    interface PlantListItem {
    }
}
declare global {
    interface HTMLPlantCardElement extends Components.PlantCard, HTMLStencilElement {
    }
    var HTMLPlantCardElement: {
        prototype: HTMLPlantCardElement;
        new (): HTMLPlantCardElement;
    };
    interface HTMLPlantListElement extends Components.PlantList, HTMLStencilElement {
    }
    var HTMLPlantListElement: {
        prototype: HTMLPlantListElement;
        new (): HTMLPlantListElement;
    };
    interface HTMLPlantListItemElement extends Components.PlantListItem, HTMLStencilElement {
    }
    var HTMLPlantListItemElement: {
        prototype: HTMLPlantListItemElement;
        new (): HTMLPlantListItemElement;
    };
    interface HTMLElementTagNameMap {
        "plant-card": HTMLPlantCardElement;
        "plant-list": HTMLPlantListElement;
        "plant-list-item": HTMLPlantListItemElement;
    }
}
declare namespace LocalJSX {
    interface PlantCard {
        "hostRole"?: 'button' | 'link';
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "role"?: 'button' | 'link';
    }
    interface PlantList {
    }
    interface PlantListItem {
    }
    interface IntrinsicElements {
        "plant-card": PlantCard;
        "plant-list": PlantList;
        "plant-list-item": PlantListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "plant-card": LocalJSX.PlantCard & JSXBase.HTMLAttributes<HTMLPlantCardElement>;
            "plant-list": LocalJSX.PlantList & JSXBase.HTMLAttributes<HTMLPlantListElement>;
            "plant-list-item": LocalJSX.PlantListItem & JSXBase.HTMLAttributes<HTMLPlantListItemElement>;
        }
    }
}
